const projects = [
  {
    name: 'CarsRental',
    description: 'This app is meant for us to book a car, add a car, reserve a car, and delete a car.',
    live_demo: 'https://622110fecccae53070225c23--cars-microverse-cap.netlify.app/',
    source_code: 'https://github.com/AmineHLub/Cars-Frontend',
    image: 'https://repository-images.githubusercontent.com/466200615/37ed53c8-9aa7-4f1e-942a-69121e457af7',
    languages: ['ReactJS', 'Redux', 'React Router', 'CSS'],
  },
  {
    name: 'Calculator',
    description: 'A website where you can use our calculator for your math problems.',
    live_demo: 'https://mathsmagician.netlify.app/',
    source_code: 'https://github.com/sheylaPozo/math.magicians',
    image: 'https://repository-images.githubusercontent.com/397948172/935cfe23-e8a4-447e-8c8b-c805e9d78a89',
    languages: ['JavaScript', 'HTML5', 'CSS'],
  },
  {
    name: 'BakerySite',
    description: 'This is a bakery website that displays some of the cakes of a cheff pastry`s online business.',
    live_demo: 'https://sheylapozo.github.io/Capstone-Bakery/',
    source_code: 'https://github.com/sheylaPozo/Capstone-Bakery',
    image: 'https://repository-images.githubusercontent.com/383429699/a60dd650-d89e-42f5-9a0d-85facdc26f3c',
    languages: ['HTML5', 'CSS', 'JavaScript'],
  },
  {
    name: 'Leaderboard',
    description: 'The leaderboard website displays scores submitted by different players. It also allows you to submit your score. All data is preserved thanks to the external Leaderboard API service.',
    live_demo: 'https://sheylapozo.github.io/leaderboard/',
    source_code: 'https://github.com/sheylaPozo/leaderboard',
    image: 'https://repository-images.githubusercontent.com/392910104/ba7998c7-3c03-4757-bb57-abf8c5644a30',
    languages: ['HTML5', 'CSS', 'JavaScript', 'Webpack'],
  },
  {
    name: 'OOP School Library',
    description: 'This app is a tool one can use in a library to record what books are in the library and who borrows them. This app will allow a you to: Add new students or teachers.Add new books. Save records of who borrowed a given book and when.',
    live_demo: '',
    source_code: 'https://github.com/sheylaPozo/schoolLibrary',
    image: 'https://repository-images.githubusercontent.com/416720764/24feb8f9-bb60-45b0-b67e-a715b7a24253',
    languages: ['Ruby', 'RSpec'],
  },
  {
    name: 'MetricsApp Covid',
    description: 'This project is a mobile web application used to check a list of COVID-19 metrics worldwide.',
    live_demo: 'https://southamericacovid19.netlify.app/',
    source_code: 'https://github.com/sheylaPozo/metricsapp',
    image: 'https://user-images.githubusercontent.com/54015740/133807112-e81b2004-f0fc-42ce-9d0e-922d8a76a54a.png',
    languages: ['ReactJS', 'Redux', 'CSS'],
  },
  {
    name: "Space Travelers' Hub",
    description: 'This web application is built for a company that provides commercial and scientific space travel services. The application allows users to book rockets and join selected space missions.',
    live_demo: 'https://spacetraveler.netlify.app/',
    source_code: 'https://github.com/m05e5/react_group_project',
    image: 'https://user-images.githubusercontent.com/54015740/132718531-3acebf08-0a4c-42d7-b188-6b9f3c5cc275.png',
    languages: ['ReactJS', 'CSS'],
  },
  {
    name: 'BudgetApp',
    description: 'A mobile web application where you can manage your budget: you have a list of transactions associated with a category, so that you can see how much money you spent and on what.',
    live_demo: 'https://budgetapps.herokuapp.com/',
    source_code: 'https://github.com/sheylaPozo/budgetapp',
    image: 'https://repository-images.githubusercontent.com/434039976/d836d24d-d3e0-454b-bbde-5fc96ad2ee3c',
    languages: ['Ruby', 'RoR', 'CSS', 'BootStrap'],
  },
];

export default projects;
